spring:
  datasource:
#    driverClassName: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:mem:test;
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: password
#    hikari:
#      maximum-pool-size: 5
#      connection-timeout: 60000
#    h2:
#      console:
#        enabled: true

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#        dialect: org.hibernate.dialect.H2Dialect

  jackson:
    serialization:
      write-dates-as-timestamps: false
